name:Android CI

on:
  push:
    branches:["main"]
    pull:
      branches:["main"]

jobs:
  build:
      name:  Build
      runs-on:  ubantu-latest
      steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "This job is running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Checkout
        uses: actions/checkout@v4.1.7
           - run: echo "The ${{ github.repository }} repository has been cloned."
      - run: echo "Setting up JDK"
      - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
       with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle
      - run: echo "The workflow is now ready to test your code."
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - run: echo "Building Debug APK."
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.1
        with: 
          name: AndroidCICD-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
        
      - run: echo "Build status report=${{ job.status }}."
      
  
